default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development: *default
test: *default
production: *default
